---
name: App-Sequence
version: 0.01_03
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: useful plaggable subroutine engine.
license: perl
resources:
  license: ~
requires:
  Config::Tiny: 0
  Simo: 0
  Text::CSV: 0
  XML::Simple: 0
  YAML: 0
build_requires:
  Test::More: 0
provides:
  App::Sequence:
    file: lib/App/Sequence.pm
    version: 0.01_03
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
