---
name: App-Sequence
version: 0.0502
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: subroutine engine
license: perl
resources:
  license: ~
requires:
  Config::Tiny: 0
  Encode: 0
  JSON: 2
  Object::Simple: 0.0201
  Text::CSV: 0
  XML::Simple: 0
  YAML: 0
build_requires:
  IO::Capture: 0
  Test::More: 0
provides:
  App::Sequence:
    file: lib/App/Sequence.pm
    version: 0.0502
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
